### ISSUE TITLE
Minify the distribution file

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#98]
## First Timers Only

Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20) issues. Thanks!

## The Problem

Image Sequencer has a lot of source files and hence the distribution ends up being pretty large, we can do our bit by minifying the distribution file.

All the source files are located in [./src/](https://github.com/publiclab/image-sequencer/tree/master/src)

## The Solution

Grunt has different modules for different tasks. One such module is [grunt-contrib-uglify](https://www.npmjs.com/package/grunt-contrib-uglify). This package will uglify(or minify) your JS files so that they take less space (by removing whitespaces, line breaks and comments).

What you'll have to do is install this module as a developer dependancy by doing this:

```
image-sequencer $ npm install --save-dev grunt-contrib-uglify
```

Now you can use this in Image Sequencer. What grunt does is defined in the Gruntfile ( [./Gruntfile.js](https://github.com/publiclab/image-sequencer/tree/master/Gruntfile.js) ) 

There is a task "build" defined in the Gruntfile. In the build task, what is already being done is that the src files are browserified into one single distribution file.

In the same task, add the grunt-contrib-minify such that the `./dist/image-sequencer.js` generated above is minified and exported as `./dist/image-sequencer.min.js`.

## Steps to Fix
- [ ] Claim this issue with a comment here, and ask for any issues/clarifications.
- [ ] Clone this repository locally.
- [ ] Try to fix the issue as described above, but even before you have completed doing so, you can:
- [ ] Commit your work and initiate a Pull Request (Mark it as `work-needed` if you haven't completed the work on the issue)

**Comment by divyamamgai** [comment]
Can I take up this issue? I want to get started with Open Source contribution and this seems a good place to start since I already have experience with this.

**Comment by ccpandhare** [comment]
Sure!!
:-)

**Comment by divyamamgai** [comment]
Can you guide as to how do I initiate the build?

**Comment by ccpandhare** [comment]
As far as I know, There's no ES6 code...
The dependencies might be using ES6.

**Comment by ccpandhare** [comment]
What was the problem you faced?

**Comment by divyamamgai** [comment]
const keyword is used which is in the spec for ES6 but not the previous ones, so uglify is throwing unknown keyword exception. Maybe we can just change them to var?

**Comment by ccpandhare** [comment]
Ohh okay. I see.
Yes I think that can be done. Will have a look. Thanks!

**Comment by divyamamgai** [comment]
Do you want me to do those changes in this PR or are you going to do those in a separate one?

**Comment by ccpandhare** [comment]
I first need to check whether that breaks anything else; will do that soon.

**Comment by ccpandhare** [comment]
Fixed that in #104 
Thanks for you patience and sorry for the delay!

**Comment by divyamamgai** [comment]
Okay I'll pull the latest and start working on this PR.

**Comment by ccpandhare** [comment]
Thanks!

**Comment by divyamamgai** [comment]
Hey, on doing grunt build I'm still getting `const` variables in the dist js. Can you help? I have forked the latest master.

**Comment by ccpandhare** [comment]
Ohh is it? Will have a look. Thanks!

I think it is pretty safe to replace const with var, because we haven't
used them for a particular reason.

Will check.

**Comment by ccpandhare** [comment]
I checked. Some more "const"s were there; I removed the const identifiers from our code, but one of our dependencies has it. So we will have to go ahead with a solution which supports ES6.

**Comment by divyamamgai** [comment]
Okay, I'll look into the ES6 supporting solution, it had some issues but I'll keep you posted.

**Comment by makeupsomething** [comment]
If this is still available id love to have a go at it

**Comment by ccpandhare** [comment]
Sure, that'd be great!!

**Comment by divyamamgai** [comment]
I'm sorry, but I have got some urgent work to take care so yeah you can go ahead and to this.

**Comment by nataliemcmullen** [comment]
First timer here. Can I take a stab at this?

**Comment by jywarren** [comment]
Of course, thank you!

**Comment by divyamamgai** [comment]
Is this still open? I see that in the master uglify task has been added and is working using the harmony branch of grunt-contrib-uglify.

**Comment by jywarren** [comment]
ah, perhaps you're right; @ccpandhare, if this is complete could you close
this issue?

Divya - do any other issues look interesting to you? Thanks!

**Comment by divyamamgai** [comment]
Sorry, but currently I'm occupied with something. I'll finish that up in two weeks. After that I will take up an issue to resolve.

**Comment by makeupsomething** [comment]
@jywarren @divyamamgai @ccpandhare 
Sorry, i made a pull request for this issues a while back and didn't realise it had been merged already.

**Comment by jywarren** [comment]
Ah, well, it looks like this is indeed resolved so I'll close it. Sorry for the confusion folks, and we've been adding new issues we'd love help with! Thank you all very much!

**Comment by jywarren** [comment]
Addressed in https://github.com/publiclab/image-sequencer/pull/124
